openapi: 3.0.0
info:
  title: Cheat Buster API
  description: API to search fake dating profiles by email
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/search:
    get:
      summary: Search user by email
      parameters:
        - name: email
          in: query
          required: true
          description: Email to search
          schema:
            type: string
            format: email
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid email format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        age:
          type: integer
        city:
          type: string
        picture:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
